# Build a Unified Kernel Image instead of a separate initramfs
uefi="yes"

# Only include what this exact machine needs
hostonly="yes"
hostonly_mode="strict"
hostonly_cmdline="yes"

# Filesystem is plain ext4 on /dev/mmcblk0p3
filesystems+=" ext4 "

#omit_dracutmodules+=" udev-rules "
#omit_dracutmodules+=" drm kernel-modules-extra "


# We don’t need any of this for your setup
omit_dracutmodules+="
    resume
    qemu
    virtiofs
    crypt
    btrfs
    zfs
    lvm
    mdraid
    dm
    multipath
    iscsi
    nfs
    cifs
    fcoe
    network
    ifcfg
    clevis
    dracut-systemd
    systemd
    nvdimm
    watchdog
    rngd
    plymouth
"

# Don’t copy firmware blobs into the UKI
#nofirmware="yes"

# Fast decompression for tiny init time
compress="lz4"

# Your kernel command line (goes into the UKI’s .cmdline section).
# Keep what you had, it’s good.
kernel_cmdline="quiet loglevel=4 rd.udev.log_level=3 rd.luks=0 rd.lvm=0 rd.md=0 rd.dm=0 rootfstype=ext4 i915.enable_psr=1 i915.enable_dc=2 i915.enable_fbc=1 noresume mitigations=off nmi_watchdog=0 iomem=relaxed mem_sleep_default=deep"
# uefi_secureboot_cert="/var/lib/sbctl/keys/db/db.pem"
# uefi_secureboot_key="/var/lib/sbctl/keys/db/db.key"
