[helpers]

[default]
depends = []

[default.files]
"61-pixel-keyboard.hwdb" = "/etc/udev/hwdb.d/61-pixel-keyboard.hwdb"
"tlp.conf" = "/etc/tlp.conf"
"10-uki.conf" = "/etc/dracut.conf.d/10-uki.conf"
"30-uki-rotate" = "/etc/kernel.d/post-install/30-uki-rotate"
"dracut-uefi-hook" = "/etc/default/dracut-uefi-hook"

[default.variables]

[settings]
default_target_type = "automatic"
